<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<Authors>Hide</Authors>
	<Company>Hide Works</Company>
    <Version>1.1.0</Version>
	<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
	<NeutralLanguage>ja-JP</NeutralLanguage>
	<ApplicationIcon>Assets\HideWorks.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\HideWorks.ico" />
  </ItemGroup>

</Project>
